version: '2'
services:
  bash:
    build: .
    command: bash
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"

  api:
    image: jekyll/jekyll
    container_name: github-blog-local
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'jekyll serve -s /usr/src/app --watch'
    ports:
      - "4000:4000"
